package io.hacksy.util.fluent;

public class CaughtException extends RuntimeException {
  public CaughtException(Throwable cause) {
    super(cause);
  }
}
